# Generated by Django 5.1.2 on 2026-05-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='demo_balance',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=12),
        ),
    ]
