# Generated by Django 5.1.2 on 2026-05-12 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_demo_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_pitch_lines',
            field=models.JSONField(blank=True, default=list, help_text='Список коротких строк для карточки исполнителя.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_specialization',
            field=models.CharField(blank=True, help_text='Подпись на карточке на главной (например «Копирайтинг»).', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='kyc_status',
            field=models.CharField(choices=[('none', 'Не подавали'), ('pending', 'На проверке'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_other',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_telegram',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_vk',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('link', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='accounts.profile')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
