# Generated by Django 5.1.2 on 2026-05-12 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_avatar_profile_card_pitch_lines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_arbitrator',
            field=models.BooleanField(default=False, help_text='Может выносить решения по спорам на арбитраже.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_moderator',
            field=models.BooleanField(default=False, help_text='Доступ к очереди модерации заданий и KYC.'),
        ),
        migrations.CreateModel(
            name='KycDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('id_front', 'Документ (лицевая)'), ('id_back', 'Документ (оборот)'), ('selfie', 'Селфи с документом'), ('other', 'Другое')], default='id_front', max_length=20)),
                ('file', models.FileField(upload_to='kyc/')),
                ('note', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to='accounts.profile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
