# Generated by Django 5.1.2 on 2026-05-12 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_moderator_kyc_push_disputes'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(blank=True, help_text='Раздел портфолио (специализация).', max_length=120),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='tools_skills',
            field=models.JSONField(blank=True, default=list, help_text='До 20 инструментов и навыков.'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube, RuTube, Vimeo и т.п.'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/', verbose_name='Обложка'),
        ),
        migrations.CreateModel(
            name='PortfolioItemGalleryFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='portfolio/gallery/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_files', to='accounts.portfolioitem')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
