# Generated by Django 5.1.2 on 2026-05-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_is_contest_job_is_exchange_jobbid"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="country",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="job",
            name="is_urgent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="subcategory",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="job",
            name="city",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
