# Generated by Django 5.1

import django.utils.timezone
from django.db import migrations, models


def backfill_completed_at(apps, schema_editor):
    Job = apps.get_model("jobs", "Job")
    JobStatusUpdate = apps.get_model("jobs", "JobStatusUpdate")
    for job in Job.objects.filter(status="completed").iterator():
        if getattr(job, "completed_at", None):
            continue
        upd = (
            JobStatusUpdate.objects.filter(job_id=job.pk, status="completed")
            .order_by("-created_at")
            .first()
        )
        if upd:
            job.completed_at = upd.created_at
            job.save(update_fields=["completed_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_country_job_is_urgent_job_subcategory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Момент перевода задания в «Завершено»; начало 14-дневного окна отзывов.",
                null=True,
                verbose_name="Закрытие контракта",
            ),
        ),
        migrations.RunPython(backfill_completed_at, migrations.RunPython.noop),
    ]
