# Generated by Django 5.1.2 on 2026-05-12 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='moderation_note',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='job',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Одобрено'), ('pending', 'На модерации'), ('rejected', 'Отклонено')], default='approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('open', 'Открыто'), ('in_progress', 'В работе'), ('submitted', 'Ожидает проверки'), ('disputed', 'Спор'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobstatusupdate',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('open', 'Открыто'), ('in_progress', 'В работе'), ('submitted', 'Ожидает проверки'), ('disputed', 'Спор'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], max_length=20),
        ),
        migrations.CreateModel(
            name='JobDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('resolved', 'Закрыт')], default='open', max_length=20)),
                ('summary', models.TextField()),
                ('previous_job_status', models.CharField(blank=True, max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='jobs.job')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='jobs.job')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JobSpecRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_description', models.TextField()),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_spec_edits', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_revisions', to='jobs.job')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
