# Generated by Django 5.1.2 on 2026-05-12 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_moderation_note_job_moderation_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdispute',
            name='arbitrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arbitrated_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobdispute',
            name='arbitrator_decision',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobdispute',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobdispute',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('escalated', 'На арбитраже'), ('resolved', 'Закрыт')], default='open', max_length=20),
        ),
    ]
